// characters.js — Dvapara Yuga Lineage Cosmos v3
// Fields: id, name, sanskrit, epithet, gender, gen, clan, importance, allegiance, chiranjeevi, avatar, weapon, desc

const characters = [

// ── Gen 0 · Primordials ──────────────────────────────────────────────────────
{ id:"Brahma", name:"Brahma", sanskrit:"ब्रह्मा", epithet:"The Creator", gender:"other", gen:0, clan:"Divine", importance:"high", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:"Brahmastra — the supreme divine weapon born of his will", desc:"The four-faced creator deity who brought the universe into existence from the cosmic void. All lineages of gods, sages, and kings ultimately trace their origin to Brahma's act of creation. He is the grandfather of the cosmos, called Prajapati and Pitamaha." },

{ id:"Atri", name:"Atri", sanskrit:"अत्रि", epithet:"Saptarishi — One of the Seven Seers", gender:"male", gen:0, clan:"Divine", importance:"medium", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:"Tapas (ascetic fire) — power of intense penance", desc:"One of the seven mind-born sons of Brahma and a venerated Saptarishi. Through profound meditation Atri's eyes blazed with such brilliance that the Moon god Chandra was born from them. His hermitage on Mount Riksha was a seat of cosmic learning." },

{ id:"Anasuya", name:"Anasuya", sanskrit:"अनसूया", epithet:"Embodiment of Chastity", gender:"female", gen:0, clan:"Divine", importance:"medium", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:null, desc:"The supremely devoted wife of sage Atri, celebrated across all three worlds for her unwavering chastity. When the Trimurti — Brahma, Vishnu, and Shiva — tested her virtue in disguise, she transformed them into infants, demonstrating a power born solely of pure love. She is the mother of Chandra, Durvasa, and Dattatreya." },

// ── Gen 1 · Lunar Origin ──────────────────────────────────────────────────────
{ id:"Chandra", name:"Chandra", sanskrit:"चन्द्र", epithet:"Soma — Lord of the Moon", gender:"male", gen:1, clan:"Divine", importance:"high", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:"Lunar nectar (Amrita) — power of healing and growth", desc:"The resplendent Moon god born from Atri's penance, who became lord of all plant life, the night sky, and the minds of all beings. He is the progenitor of the entire Chandravamsha — the Lunar Dynasty from which the Pandavas and Kauravas both descend. His illicit union with Tara, wife of Brihaspati, triggered the great celestial war known as Tarakamaya." },

{ id:"Tara", name:"Tara", sanskrit:"तारा", epithet:"Star Goddess, Wife of Brihaspati", gender:"female", gen:1, clan:"Divine", importance:"medium", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:null, desc:"The radiant wife of Brihaspati, preceptor of the gods. Chandra abducted her in his intoxicated longing, igniting the Tarakamaya war that split the cosmos between gods and asuras. From their union was born Budha, the planet Mercury, whose lineage would produce the Lunar Dynasty's great kings. Tara's return to Brihaspati ended the celestial conflict." },

// ── Gen 2 · Early Lunar ───────────────────────────────────────────────────────
{ id:"Budha", name:"Budha", sanskrit:"बुध", epithet:"Lord of Mercury", gender:"male", gen:2, clan:"Divine", importance:"medium", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:null, desc:"Son of Chandra and Tara, and the divine embodiment of the planet Mercury. He is celebrated for supreme intelligence and eloquence. His marriage to the shapeshifting princess Ila — born male as Sudyumna but transformed female by Shiva's curse — founded the terrestrial line of Lunar kings that would culminate in the Mahabharata." },

{ id:"Ila", name:"Ila", sanskrit:"इला", epithet:"The Twice-Born — Prince and Princess", gender:"other", gen:2, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Born as the prince Sudyumna, son of Manu, Ila strayed into a sacred forest of Shiva and Parvati and was transformed into a woman. Each month spent in and out of Shiva's grove alternated between male and female existence. As Ila, she wed Budha and bore Pururavas; as Sudyumna, he fathered other sons — making Ila a uniquely dual ancestor of the Lunar line." },

// ── Gen 3 · Pururavas Era ─────────────────────────────────────────────────────
{ id:"Pururavas", name:"Pururavas", sanskrit:"पुरूरवस्", epithet:"The Brilliant One", gender:"male", gen:3, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"The great king who fell hopelessly in love with the celestial apsara Urvashi and persuaded her to live on earth as his wife for many years. Their parting, caused by a trick of the Gandharvas, is immortalised in Kalidasa's Vikramorvasiyam. He is the first truly human king in the Lunar lineage and the direct ancestor of both Yayati and the Mahabharata clans." },

{ id:"Urvashi", name:"Urvashi", sanskrit:"उर्वशी", epithet:"Loveliest of Apsaras", gender:"female", gen:3, clan:"Divine", importance:"medium", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:null, desc:"The most beautiful of all celestial nymphs, she descended to earth out of love for King Pururavas. Their union lasted centuries and produced the sons who became ancestors of the Puru and Yadu lines. She later rejected Arjuna's advances in Indra's court, cursing him to live as a eunuch — a curse that became his disguise during the year of hiding in Virata's kingdom." },

// ── Gen 4 · Early Kings ───────────────────────────────────────────────────────
{ id:"Ayu", name:"Ayu", sanskrit:"आयु", epithet:"King Ayu", gender:"male", gen:4, clan:"Kuru", importance:"low", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Son of Pururavas and Urvashi, Ayu was the first mortal king fully born of the Lunar line. His reign consolidated the early Chandravamsha kingdom. He is the grandfather of Yayati and the great ancestor through whom both the Puru and Yadu clans trace descent." },


// ── Gen 5 ─────────────────────────────────────────────────────────────────────
{ id:"Nahusha", name:"Nahusha", sanskrit:"नहुष", epithet:"The King Who Became Indra", gender:"male", gen:5, clan:"Kuru", importance:"low", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"A mighty king of the Lunar line who briefly occupied Indra's throne while Indra hid after slaying Vritra. Drunk with celestial power, Nahusha demanded the sage Agastya carry his palanquin, then kicked him — Agastya cursed him to become a python for a thousand years. His fall is the Mahabharata's great lesson on the corruption of pride and arrogance." },

// ── Gen 6 ─────────────────────────────────────────────────────────────────────
{ id:"Yayati", name:"Yayati", sanskrit:"ययाति", epithet:"The Eternal Youth-Seeker", gender:"male", gen:6, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Son of Nahusha and one of the great ancestral kings, Yayati married both Devayani and Sharmishtha, thus uniting the lineages of Shukracharya and Vrishaparva. Cursed with premature old age by Shukracharya for his infidelity, he borrowed youth from his youngest son Puru. After a thousand years of pleasure he returned it, blessing Puru as his heir — the act that gave birth to the Puru dynasty and, ultimately, the Kuru clan." },

{ id:"Devayani", name:"Devayani", sanskrit:"देवयानी", epithet:"Daughter of Shukracharya", gender:"female", gen:6, clan:"Divine", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"The proud and fiercely intelligent daughter of Shukracharya, the preceptor of the asuras. After being pushed into a well by Sharmishtha, she secured Yayati's hand in marriage as compensation. She bore Yadu and Turvasu. When she discovered Yayati's secret marriage to Sharmishtha, she invoked her father's curse that ended Yayati's youth — a fateful act that reshaped the Lunar Dynasty's succession." },

{ id:"Sharmishtha", name:"Sharmishtha", sanskrit:"शर्मिष्ठा", epithet:"Asura Princess, Hidden Queen", gender:"female", gen:6, clan:"Divine", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Princess of the asura king Vrishaparva and daughter of his court, she was given as a servant to Devayani as penance for pushing her into a well. In secret she became Yayati's second wife and bore him three sons — Druhyu, Anu, and Puru. Her son Puru's selfless gift of youth to his father made him heir to the throne, and through Puru flows the entire Kuru bloodline." },

// ── Gen 7 ─────────────────────────────────────────────────────────────────────
{ id:"Puru", name:"Puru", sanskrit:"पुरु", epithet:"The Dutiful Son", gender:"male", gen:7, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"The youngest son of Yayati and Sharmishtha, Puru alone agreed to bear his father's curse of old age so Yayati could reclaim youth. After a thousand years of pleasures, Yayati acknowledged that desire is never satiated and returned Puru's youth, naming him sole heir over his elder brothers. All subsequent Kuru kings — Bharata, Shantanu, Dhritarashtra, Pandu — descend from Puru." },

{ id:"Yadu", name:"Yadu", sanskrit:"यदु", epithet:"Patriarch of the Yadavas", gender:"male", gen:7, clan:"Yadava", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"The eldest son of Yayati and Devayani, Yadu refused to take his father's old age and was therefore disinherited from the main throne. Yet his lineage became the mightiest of all — for from Yadu descended the Yadava clan, and from the Yadavas came Sri Krishna, avatar of Vishnu. His disinheritance was a cosmic design ensuring Krishna's birth outside the ruling Kuru line." },

// ── Gen 8 ─────────────────────────────────────────────────────────────────────
{ id:"Dushyanta", name:"Dushyanta", sanskrit:"दुष्यन्त", epithet:"The Wandering King", gender:"male", gen:8, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"A celebrated king of the Puru line, famous for his fateful meeting with Shakuntala at Sage Kanva's hermitage. After a gandharva marriage and a passionate union, he left promising to send for her — then forgot everything under a celestial curse. Only when Shakuntala presented their son Bharata's birthmark ring did memory return. His story is immortalised in Kalidasa's Abhijnanashakuntalam." },

{ id:"Shakuntala", name:"Shakuntala", sanskrit:"शकुन्तला", epithet:"The Forest Daughter", gender:"female", gen:8, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Born of the apsara Menaka and sage Vishwamitra, abandoned at birth and raised by the sage Kanva in his forest hermitage. She married King Dushyanta in a gandharva ceremony and bore the mighty Emperor Bharata. Cursed by Durvasa to be forgotten by her love, she wandered alone until fate reunited her with Dushyanta. Her story is one of the Mahabharata's most beautiful and heartbreaking tales of love and loss." },

// ── Gen 9 ─────────────────────────────────────────────────────────────────────
{ id:"Bharata", name:"Bharata", sanskrit:"भरत", epithet:"Chakravartin — Emperor of All", gender:"male", gen:9, clan:"Kuru", importance:"high", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:"Chakra — divine discus of universal sovereignty", desc:"The supreme emperor after whom the entire Indian subcontinent is named Bharatavarsha. Son of Dushyanta and Shakuntala, he conquered all kingdoms from sea to sea and performed a hundred Ashwamedha horse sacrifices. The Mahabharata is literally 'the great story of the descendants of Bharata.' His rule established the gold standard of righteous kingship that all his heirs aspired to match." },

// ── Gen 10 ────────────────────────────────────────────────────────────────────
{ id:"Kuru", name:"Kuru", sanskrit:"कुरु", epithet:"Patriarch of the Kuru Clan", gender:"male", gen:10, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"The great ancestor who gave his name to the entire Kuru dynasty, to Kurukshetra (the field he personally ploughed and consecrated with his own blood), and to the Kauravas and Pandavas alike. A king of extraordinary austerity, he transformed Kurukshetra into the holiest of tirthas, promising that any who died there — even sinners — would attain heaven. The Mahabharata war was fought on his sacred ground." },


// ── Gen 11 ────────────────────────────────────────────────────────────────────
{ id:"Pratipa", name:"Pratipa", sanskrit:"प्रतीप", epithet:"Grandfather of Shantanu", gender:"male", gen:11, clan:"Kuru", importance:"low", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"A just and venerated king of the Kuru line, father of Devapi, Bahlika, and Shantanu. When the goddess Ganga once sat on his right thigh — the side reserved for wives — he gently redirected her, prophesying she would instead become the wife of his son Shantanu. This small act of cosmic courtesy set in motion the birth of Bhishma and the entire Mahabharata chain of events." },

{ id:"Sunanda", name:"Sunanda", sanskrit:"सुनन्दा", epithet:"Queen of Pratipa", gender:"female", gen:11, clan:"Kuru", importance:"low", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"The devoted queen of King Pratipa and mother of the three Kuru princes — Devapi, Bahlika, and the future king Shantanu. Though her role in the epic is modest, she is the maternal root of the Hastinapura royal line that would produce Bhishma, Dhritarashtra, Pandu, and all the warriors of the great war." },

{ id:"Parashara", name:"Parashara", sanskrit:"पराशर", epithet:"Sage Parashara", gender:"male", gen:11, clan:"Divine", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:"Brahmastra and mastery of all Vedic knowledge", desc:"A great Vedic sage and grandson of Vasishtha, Parashara encountered the fisherman's daughter Satyavati while crossing a river. Their union on a mist-shrouded island produced the incomparable sage-poet Vyasa, compiler of the Vedas and author of the Mahabharata. Parashara gifted Satyavati with a permanent fragrance before parting, and restored her maidenhood so the encounter left no trace." },

{ id:"Bharadwaja", name:"Bharadwaja", sanskrit:"भरद्वाज", epithet:"Sage of Cosmic Science", gender:"male", gen:11, clan:"Divine", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:"Mastery of Dhanurveda — the complete science of weapons", desc:"One of the greatest Saptarishis, Bharadwaja performed penance so severe that Indra himself was moved to offer him a boon. In a moment of metaphysical honesty he chose infinite knowledge — only to learn that what a mortal can grasp is like a handful of earth beside a mountain. He is the father of Dronacharya, and it was from his hermitage that Drona mastered all known weaponry before becoming guru to the Kuru princes." },

// ── Gen 12 ────────────────────────────────────────────────────────────────────
{ id:"Shantanu", name:"Shantanu", sanskrit:"शन्तनु", epithet:"He Whose Touch Heals", gender:"male", gen:12, clan:"Kuru", importance:"high", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"King of Hastinapura whose very touch was said to restore youth and health to any he blessed. His two great loves defined the Mahabharata's tragedy: his marriage to Ganga produced Bhishma, and his obsession with Satyavati led Bhishma to take the terrible vow of celibacy that distorted Kuru succession for generations. Shantanu's heart was generous but his desires shaped a dynasty's doom." },

{ id:"Ganga", name:"Ganga", sanskrit:"गङ्गा", epithet:"The Sacred River Goddess", gender:"female", gen:12, clan:"Divine", importance:"high", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:null, desc:"The divine goddess of the holy Ganges river who descended to earth and married King Shantanu under one condition — he must never question her actions. She drowned seven of their newborn sons in the river, releasing the Vasus from a sage's curse, before Shantanu intervened to save the eighth — Devavrata, who became Bhishma. Her departure when Shantanu broke his oath ended the most extraordinary marriage in the epic." },

{ id:"Satyavati", name:"Satyavati", sanskrit:"सत्यवती", epithet:"The Fragrant Fisherwoman Queen", gender:"female", gen:12, clan:"Kuru", importance:"high", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Born of a fisherman and the apsara Adrika, Satyavati carried the scent of fish until Parashara's blessing turned it into an intoxicating perfume. She bore Vyasa to Parashara before marrying Shantanu, becoming queen of Hastinapura. After both her sons Chitrangada and Vichitravirya died without heirs, she invoked her firstborn Vyasa to father sons through Niyoga — the act that produced Dhritarashtra, Pandu, and Vidura." },

{ id:"Vyasa", name:"Vyasa", sanskrit:"व्यास", epithet:"Krishna Dwaipayana — Compiler of the Vedas", gender:"male", gen:12, clan:"Divine", importance:"high", allegiance:"Neutral", chiranjeevi:true, avatar:null, weapon:"Brahma Jnana — supreme divine wisdom beyond all weapons", desc:"The immortal sage-poet born of Parashara and Satyavati on a river island — hence also called Dvaipayana. He split the single Veda into four, composed the eighteen Puranas, and authored the Mahabharata with 100,000 verses. A Chiranjeevi, he walked the earth long after the war, narrating the epic to Ganesha who wrote it. Through Niyoga with Ambika, Ambalika, and Parishrami he fathered Dhritarashtra, Pandu, and Vidura — making him biological grandfather of all the warring princes." },

{ id:"Shurasena", name:"Shurasena", sanskrit:"शूरसेन", epithet:"Yadava Chieftain", gender:"male", gen:12, clan:"Yadava", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"A powerful Yadava king and grandfather of both Vasudeva and Kunti. He gave his firstborn daughter Pritha in adoption to his childless cousin Kuntibhoja — she became known as Kunti. This adoption was the thread that wove together the Yadava and Kuru destinies: Kunti would marry Pandu and mother the three eldest Pandavas, uniting the two greatest dynasties of Dvapara Yuga." },

{ id:"Ugrasena", name:"Ugrasena", sanskrit:"उग्रसेन", epithet:"King of Mathura", gender:"male", gen:12, clan:"Yadava", importance:"medium", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"The rightful king of Mathura of the Bhoja Yadava clan, father of the tyrant Kamsa and of Devaki. He was overthrown and imprisoned by his own son Kamsa, who usurped the throne after hearing a prophecy that Devaki's eighth child would slay him. After Krishna killed Kamsa, he restored the throne to Ugrasena and himself served as the old king's minister — an act of profound humility from an avatar of Vishnu." },


// ── Gen 12 cont. ──────────────────────────────────────────────────────────────
{ id:"Devapi", name:"Devapi", sanskrit:"देवापि", epithet:"The Hermit Prince", gender:"male", gen:12, clan:"Kuru", importance:"low", allegiance:"Pre-war", chiranjeevi:true, avatar:null, weapon:null, desc:"Elder brother of Shantanu who renounced the Kuru throne due to a skin affliction and retired to the Himalayas as an ascetic. Per prophecy, he is a Chiranjeevi who will return at the dawn of the next Satya Yuga to re-establish dharma as king. His abdication left Shantanu to inherit Hastinapura, setting the Mahabharata's dynastic succession in motion." },

{ id:"Bahlika", name:"Bahlika", sanskrit:"बाह्लीक", epithet:"The Elder of Hastinapura", gender:"male", gen:12, clan:"Kuru", importance:"low", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"Second son of Pratipa and elder uncle of Bhishma, Bahlika chose to rule the kingdom of Bahlika (Bactria) inherited from his maternal uncle rather than stay at Hastinapura. He and his son Somadatta nonetheless fought on the Kaurava side in the Kurukshetra war out of clan loyalty. Bahlika was slain by Bhima on the fourteenth day of battle — one of the oldest warriors to fall." },

// ── Gen 13 ────────────────────────────────────────────────────────────────────
{ id:"Bhishma", name:"Bhishma", sanskrit:"भीष्म", epithet:"Devavrata — He of the Terrible Vow", gender:"male", gen:13, clan:"Kuru", importance:"high", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Brahmastra, Pashupatastra; master of all weapons taught by Parashurama", desc:"Son of Shantanu and Ganga, born the eighth Vasu Prabhasa released from mortal form. He renounced the throne and swore perpetual celibacy so his father could marry Satyavati — the most devastating vow in the epic, as it removed the most righteous warrior from ever ruling. Commander of the Kaurava army for the first ten days, he was undefeatable until his own blessing of choosing his death-hour allowed Arjuna and Shikhandi to bring him down. He lay on a bed of arrows for fifty-eight days, delivering the Shanti Parva's wisdom on dharma, before departing on Uttarayana." },

{ id:"Chitrangada", name:"Chitrangada", sanskrit:"चित्राङ्गद", epithet:"Prince of Hastinapura", gender:"male", gen:13, clan:"Kuru", importance:"low", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Eldest son of Shantanu and Satyavati, Chitrangada was a prince of immense pride who challenged a Gandharva king of the same name to combat. They fought ceaselessly for three years on the banks of the Saraswati until the Gandharva slew him, leaving Vichitravirya to inherit the empty throne of Hastinapura." },

{ id:"Vichitravirya", name:"Vichitravirya", sanskrit:"विचित्रवीर्य", epithet:"The Weak-Fated King", gender:"male", gen:13, clan:"Kuru", importance:"low", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Younger son of Shantanu and Satyavati who became king after Chitrangada's death. Bhishma abducted the three Kashi princesses for him — Amba, Ambika, and Ambalika. He married Ambika and Ambalika but died young of consumption before fathering any children, creating the succession crisis that compelled Satyavati to summon Vyasa for Niyoga." },

{ id:"Ambika", name:"Ambika", sanskrit:"अम्बिका", epithet:"Princess of Kashi", gender:"female", gen:13, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Elder of the two Kashi princesses who became Vichitravirya's queens after Bhishma's abduction from the swayamvara. When Vyasa came for Niyoga, she shut her eyes in fear at his wild appearance — and so her son Dhritarashtra was born blind. Her closed eyes sealed a dynasty's fate, for a blind king would raise a hundred sons whose blindness to dharma would destroy the world's greatest civilization." },

{ id:"Ambalika", name:"Ambalika", sanskrit:"अम्बालिका", epithet:"The Pale Queen", gender:"female", gen:13, clan:"Kuru", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"Younger Kashi princess and second wife of Vichitravirya. When Vyasa came for Niyoga she turned pale with terror — and so her son Pandu was born unnaturally pale and later cursed to never embrace a woman. Her pallor echoed across generations: Pandu's inability to father children led Kunti to invoke divine mantras, producing five sons whose war with their cousins consumed Bharatavarsha." },

{ id:"Parishrami", name:"Parishrami", sanskrit:"परिश्रमी", epithet:"The Handmaiden Queen", gender:"female", gen:13, clan:"Kuru", importance:"low", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"A wise handmaiden of the Kashi queens who met Vyasa without fear or revulsion and received him calmly during Niyoga. Her composure produced the wisest son of all three unions — Vidura, embodiment of dharma and political wisdom. Though born to a servant, Vidura's counsel was sought by gods and kings alike, and his clarity of vision surpassed that of both his royal half-brothers." },

{ id:"Somadatta", name:"Somadatta", sanskrit:"सोमदत्त", epithet:"Son of Bahlika", gender:"male", gen:13, clan:"Kuru", importance:"low", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"Son of Bahlika and father of the three warriors Bhuri, Bhurishravas, and Shala who all fought on the Kaurava side. Somadatta had a long-standing rivalry with Satyaki's grandfather that extended through generations. His son Bhurishravas was ultimately slain by Satyaki in a controversial moment during the Kurukshetra war." },

{ id:"Subala", name:"Subala", sanskrit:"सुबल", epithet:"King of Gandhara", gender:"male", gen:13, clan:"Gandhara", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"King of Gandhara (modern Kandahar) and father of Gandhari and Shakuni. He initially opposed the marriage of his daughter Gandhari to the blind Dhritarashtra, but relented under political pressure. When Dhritarashtra imprisoned Subala and his hundred sons and starved them, Subala sacrificed his own flesh to keep his youngest son Shakuni alive to exact revenge — the origin of Shakuni's undying hatred for the Kurus." },


// ── Gen 13 cont. ─────────────────────────────────────────────────────────────
{ id:"Vasudeva", name:"Vasudeva", sanskrit:"वसुदेव", epithet:"Father of Krishna", gender:"male", gen:13, clan:"Yadava", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"A noble Yadava chieftain of the Vrishni clan and son of Shurasena. On his wedding night to Devaki, a celestial voice prophesied that her eighth child would slay Kamsa — leading to his imprisonment alongside his wife. He miraculously carried the newborn Krishna across the flooded Yamuna at midnight, guided by Vishnu's divine grace. His outstretched arms and the serpent Shesha's hood sheltering the infant is one of the most iconic images of the Bhagavata Purana." },

{ id:"Devaki", name:"Devaki", sanskrit:"देवकी", epithet:"Mother of the Avatar", gender:"female", gen:13, clan:"Yadava", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"Cousin-sister of Kamsa and wife of Vasudeva, she spent her pregnancies in a dungeon watching Kamsa murder six of her newborn sons. Her seventh child Balarama was transferred to Rohini's womb. Her eighth child Krishna was secretly carried to safety in Gokul. A previous life incarnation of Aditi, she had prayed for Vishnu himself as her son — and across two lifetimes, that boon was fulfilled in the most dramatic way imaginable." },

{ id:"Rohini", name:"Rohini", sanskrit:"रोहिणी", epithet:"First Wife of Vasudeva", gender:"female", gen:13, clan:"Yadava", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"The first and most devoted wife of Vasudeva who lived safely in Nanda's Gokul during Kamsa's reign of terror. She raised Balarama after his miraculous transfer from Devaki's womb, and also lovingly raised the young Krishna in Gokul alongside her own son. Her gentle, nurturing presence was the stable home that allowed both divine brothers to grow in wisdom, strength, and love." },

{ id:"Kamsa", name:"Kamsa", sanskrit:"कंस", epithet:"The Tyrant of Mathura", gender:"male", gen:13, clan:"Yadava", importance:"high", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Immense physical strength and mastery of warfare", desc:"The villainous king of Mathura who imprisoned his own sister and brother-in-law and systematically murdered their children to escape a divine prophecy. An incarnation of the asura Kalanemi, his cruel reign terrorised the Yadavas for years. He sent a series of deadly demons to kill the child Krishna in Gokul — Putana, Trinavarta, Keshi and others — each of whom Krishna dispatched effortlessly. Finally confronted in his own arena, Krishna leapt from the wrestling ring, seized Kamsa by the hair, and hurled him to his death." },

{ id:"Drupada", name:"Drupada", sanskrit:"द्रुपद", epithet:"King of Panchala", gender:"male", gen:13, clan:"Panchala", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"King of Panchala who was humiliated by his childhood friend Drona — his own guru had sent the Kuru princes to exact half his kingdom as gurudakshina. Consumed by desire for revenge, Drupada performed an immense yajna from which Dhrishtadyumna and Draupadi were born specifically to destroy Drona. His daughter's polyandrous marriage to all five Pandavas forged the most powerful military alliance of the age." },

{ id:"Dronacharya", name:"Dronacharya", sanskrit:"द्रोणाचार्य", epithet:"Acharya — Supreme Master of Arms", gender:"male", gen:13, clan:"Kuru", importance:"high", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Brahmastra — could annihilate armies; master of all sixty-four weapons", desc:"Born miraculously in a vessel from sage Bharadwaja's semen, Drona is the greatest martial teacher of the age. He trained both the Pandavas and Kauravas in all weapons, yet fought for the Kaurava side out of loyalty to Hastinapura. He demanded Ekalavya's thumb as gurukshina — one of the epic's most debated moral acts. As commander on the fifteenth day he wreaked havoc until Yudhishthira's lie about Ashwatthama's death broke his spirit and he was beheaded by Dhrishtadyumna." },

{ id:"Kripacharya", name:"Kripacharya", sanskrit:"कृपाचार्य", epithet:"The Undying Acharya", gender:"male", gen:13, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:true, avatar:null, weapon:"Brahmastra and all sixty-four weapons of the Dhanurveda", desc:"Son of the sage Sharadvan, born along with his twin sister Kripi from reeds where their father's semen fell in astonishment at the beauty of an apsara. Kripacharya was the first weapons-teacher of the Kuru princes before Drona arrived. A Chiranjeevi, he survived the entire Kurukshetra war — one of only three warriors to do so on the Kaurava side — and became the first teacher of Parikshit in the post-war era." },

{ id:"Kripi", name:"Kripi", sanskrit:"कृपी", epithet:"Twin Sister of Kripa", gender:"female", gen:13, clan:"Kuru", importance:"low", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"Born alongside her twin Kripacharya from sage Sharadvan's semen, Kripi was raised by King Shantanu and became the devoted wife of Dronacharya. She is the mother of Ashwatthama. When Drona was treacherously killed, Kripi's grief was boundless — and her son Ashwatthama's subsequent massacre of the sleeping Pandava camp was fuelled as much by his mother's anguish as by his own rage." },

// ── Gen 14 ────────────────────────────────────────────────────────────────────
{ id:"Dhritarashtra", name:"Dhritarashtra", sanskrit:"धृतराष्ट्र", epithet:"The Blind King of Hastinapura", gender:"male", gen:14, clan:"Kuru", importance:"high", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"Born blind because his mother Ambika closed her eyes during Niyoga with Vyasa, Dhritarashtra was the eldest Kuru prince yet denied the throne for his blindness. His hundred sons were born through Gandhari's miraculous iron ball pregnancy. Though wise and well-meaning, his fatal weakness was his boundless love for Duryodhana — he consistently chose to enable his son's adharma over the counsel of Vidura, Bhishma, and even Krishna, thus becoming an unwilling architect of the Mahabharata war." },

{ id:"Pandu", name:"Pandu", sanskrit:"पाण्डु", epithet:"The Pale King", gender:"male", gen:14, clan:"Kuru", importance:"high", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:"Gandhiva-level archery; conquered all four directions for Hastinapura", desc:"Second son of Vichitravirya and Ambalika, Pandu became king due to Dhritarashtra's blindness. A brilliant military commander, he conquered kingdoms in all directions vastly expanding Hastinapura's empire. While hunting he struck a sage-couple in intimate union — the dying sage cursed him to die the moment he embraced a woman with desire. Pandu retired to the Himalayas and encouraged his wives Kunti and Madri to invoke divine mantras to produce heirs. He died touching Madri in a moment of weakness, leaving five young sons to return to Hastinapura." },


// ── Divine Fathers (Gen 14 level) ────────────────────────────────────────────
{ id:"Surya", name:"Surya", sanskrit:"सूर्य", epithet:"Aditya — The Sun God", gender:"male", gen:14, clan:"Divine", importance:"high", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:"Solar radiance — light that destroys all darkness and sin", desc:"The blazing sun god who fathered Karna after the young Kunti, curious about a divine mantra gifted by sage Durvasa, inadvertently summoned him. Surya appeared in all his glory and, bound by the mantra's power, fathered Karna — who was born with natural golden armour and earrings. Surya later warned Karna that Indra would come disguised as a brahmin to beg his kavach and kundala, but Karna gave them away anyway, choosing honour over survival." },

{ id:"Dharmaraja", name:"Dharmaraja", sanskrit:"धर्मराज", epithet:"Yama — Lord of Cosmic Justice", gender:"male", gen:14, clan:"Divine", importance:"medium", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:"Danda — the staff of death and divine justice", desc:"The god of death and dharma who fathered Yudhishthira through Kunti's divine mantra. As lord of cosmic justice he fittingly sired the most dharmic of all Pandavas — a son who never spoke an untruth in his life save for one whispered half-lie during the war. Dharmaraja tested Yudhishthira repeatedly throughout the epic, most famously as a Yaksha at a lake whose riddles revealed that his son alone truly understood dharma's deepest nature." },

{ id:"Vayu", name:"Vayu", sanskrit:"वायु", epithet:"Maruta — God of Wind", gender:"male", gen:14, clan:"Divine", importance:"medium", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:"Storm force — the breath of the cosmos itself", desc:"The god of wind and breath who fathered Bhima through Kunti's mantra, giving the Pandava his legendary physical strength — a hundred thousand war-elephants' combined might. Vayu also fathered Hanuman in another era, making Bhima and Hanuman divine brothers. Their meeting in the Mahabharata's forest section, when Hanuman blocked Bhima's path with his tail, is a celebrated scene of pride humbled by the infinite." },

{ id:"Indra", name:"Indra", sanskrit:"इन्द्र", epithet:"Shakra — King of the Gods", gender:"male", gen:14, clan:"Divine", importance:"high", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:"Vajra — the indestructible thunderbolt", desc:"King of the heavens and father of Arjuna through Kunti's mantra — a divine investment in the Pandava cause, since Indra needed a champion on earth against the forces of adharma. He later disguised himself as a brahmin to beg Karna's invincible armour and earrings, giving in return a single-use Shakti spear. Arjuna trained in Indra's heaven for a full year, mastering celestial weapons and divine dance from the apsaras." },

{ id:"AshwiniKumaras", name:"Ashwini Kumaras", sanskrit:"अश्विनीकुमार", epithet:"The Divine Twin Physicians", gender:"other", gen:14, clan:"Divine", importance:"medium", allegiance:"Divine", chiranjeevi:false, avatar:null, weapon:"Healing arts — masters of all divine medicine", desc:"The twin horsemen gods of medicine, dawn, and speed who fathered Nakula and Sahadeva through Madri's invocation of Kunti's mantra. They are the physicians of the gods, said to restore youth, heal the blind, and grant children to the childless. Their twin nature is perfectly mirrored in their sons — Nakula the most handsome of all warriors, Sahadeva the wisest in astrology and statecraft." },

// ── Gen 14 · Kuru & Gandhara Court ───────────────────────────────────────────
{ id:"Kunti", name:"Kunti", sanskrit:"कुन्ती", epithet:"Pritha — Mother of the Pandavas", gender:"female", gen:14, clan:"Kuru", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"Born Pritha, daughter of Shurasena and adopted by her uncle Kuntibhoja, she received a divine mantra from sage Durvasa that could summon any god to father a child. Before her marriage she secretly used it to test Surya's power, giving birth to the armour-clad Karna whom she set adrift in a basket on the river. As Pandu's wife she used the mantra to bear Yudhishthira, Bhima, and Arjuna, and shared it with Madri for the twins. Her whole life was shaped by sacrifice — abandoning Karna haunted her until the day she revealed the truth after his death." },

{ id:"Madri", name:"Madri", sanskrit:"माद्री", epithet:"Princess of Madra", gender:"female", gen:14, clan:"Madra", importance:"medium", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"The beautiful princess of Madra and Pandu's second wife, given to him as a gift from her brother King Shalya. Using Kunti's mantra she summoned the Ashwini Kumaras and bore the beautiful twins Nakula and Sahadeva. When Pandu died after embracing her in longing, Madri was overcome with guilt and chose to immolate herself on his funeral pyre — leaving her young sons in Kunti's care, an act of both grief and selfless love." },

{ id:"Vidura", name:"Vidura", sanskrit:"विदुर", epithet:"Dharmaraj Incarnate — The Wise Minister", gender:"male", gen:14, clan:"Kuru", importance:"high", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"Born of Parishrami the handmaiden through Niyoga with Vyasa, Vidura is considered a partial incarnation of Dharmaraja himself — born as a mortal due to a sage's curse. He served as prime minister of Hastinapura with matchless wisdom and impartiality. He consistently warned Dhritarashtra against Duryodhana's adharma, predicted the war's catastrophe, and privately aided the Pandavas throughout. He never took sides in battle — choosing dharma over clan loyalty at every turn." },

{ id:"Gandhari", name:"Gandhari", sanskrit:"गान्धारी", epithet:"The Blindfolded Queen", gender:"female", gen:14, clan:"Gandhara", importance:"high", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:"Accumulated spiritual power of lifelong blindfolded penance", desc:"Princess of Gandhara who chose to blindfold herself for life upon learning her husband Dhritarashtra was blind — an act of supreme marital devotion and quiet protest. She bore a hundred sons and one daughter through a miraculous iron ball divided by Vyasa. Her accumulated spiritual power from decades of voluntary blindness was such that when she finally removed her blindfold to look upon her son Duryodhana before the war, her gaze would have made him invincible — had Krishna not tricked him into covering his loins, leaving that area vulnerable." },

{ id:"Shakuni", name:"Shakuni", sanskrit:"शकुनि", epithet:"The Dice-Master of Destruction", gender:"male", gen:14, clan:"Gandhara", importance:"high", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Loaded dice made from his father Subala's thigh-bones — never lost a roll", desc:"Prince of Gandhara and the most cunning strategist of the age, Shakuni's entire life was shaped by a single mission: destroy the Kuru dynasty that starved his family to death. His dice were crafted from his father Subala's thigh-bones and obeyed his will. The game of dice that stripped the Pandavas of their kingdom and sent Draupadi to near-ruin was entirely his design. He died on the eighteenth day at Sahadeva's hands — who had sworn to kill him first among all enemies." },


// ── Gen 15 · War Generation ───────────────────────────────────────────────────
{ id:"Krishna", name:"Krishna", sanskrit:"कृष्ण", epithet:"Vasudeva — The Dark One, Avatar of Vishnu", gender:"male", gen:15, clan:"Yadava", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:"Vishnu", weapon:"Sudarshana Chakra, Panchajanya conch; vowed not to wield weapons at Kurukshetra", desc:"The eighth avatar of Vishnu, born to Vasudeva and Devaki in Kamsa's prison, raised by the cowherd Nanda in Gokul. As a child he slew Putana, lifted Govardhana hill, and defeated the serpent Kaliya. As king of Dwarka he became the supreme statesman, strategist, and philosopher of the age. At Kurukshetra he served as Arjuna's charioteer and delivered the Bhagavad Gita — eighteen chapters of cosmic wisdom that transformed a warrior's despair into enlightened action. He is simultaneously the most human and most divine presence in the Mahabharata." },

{ id:"Balarama", name:"Balarama", sanskrit:"बलराम", epithet:"Halayudha — The Plough-Bearer", gender:"male", gen:15, clan:"Yadava", importance:"high", allegiance:"Neutral", chiranjeevi:false, avatar:"Shesha", weapon:"Hala (plough) and Musala (mace) — weapons of earth and harvest", desc:"Elder brother of Krishna, born when Vishnu transferred him from Devaki's womb to Rohini's to save him from Kamsa. An incarnation of the cosmic serpent Shesha, Balarama possesses strength that rivals the earth itself — he once dragged the entire city of Hastinapura with his plough in fury. A master of mace combat who taught both Duryodhana and Bhima, he refused to favour either side at Kurukshetra and went on a pilgrimage along the Saraswati instead. He departed earth by the white serpent Shesha emerging from his mouth." },

{ id:"Subhadra", name:"Subhadra", sanskrit:"सुभद्रा", epithet:"Sister of Krishna and Balarama", gender:"female", gen:15, clan:"Yadava", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"The beloved sister of Krishna and Balarama, Subhadra was won by Arjuna in a divine elopement orchestrated by Krishna himself — overriding Balarama's plan to wed her to Duryodhana. She became Arjuna's third and most cherished wife and mother of the heroic Abhimanyu. Her grief at Abhimanyu's death on the thirteenth day — surrounded and slaughtered by six maharathis — is one of the Mahabharata's most heartbreaking scenes." },

{ id:"Draupadi", name:"Draupadi", sanskrit:"द्रौपदी", epithet:"Panchali — The Fire-Born Queen", gender:"female", gen:15, clan:"Panchala", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"Born of Drupada's great yajna fire alongside her brother Dhrishtadyumna, specifically to bring about Drona's destruction. The most beautiful woman of the age, she chose all five Pandavas at her swayamvara through Krishna's counsel, forging an unprecedented alliance. Her public humiliation in the Kaurava court — when Dushasana attempted to disrobe her and Duryodhana exposed his thigh — was the moment the Mahabharata war became inevitable. Her prayers to Krishna produced the miraculous unending cloth that preserved her honour. She is Shakti incarnate — the consuming fire that would not rest until her tormentors were ash." },

{ id:"Yudhishthira", name:"Yudhishthira", sanskrit:"युधिष्ठिर", epithet:"Dharmaraja — The Just King", gender:"male", gen:15, clan:"Kuru", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Spear of dharma; his chariot wheels never touched the ground until his one half-lie", desc:"Eldest Pandava, son of Kunti and Dharmaraja, Yudhishthira never spoke a full untruth in his life — his chariot rode four fingers above the ground as a mark of cosmic purity. Yet his fatal weakness was gambling; his addiction to dice led him to stake his kingdom, brothers, wife, and finally himself in Shakuni's rigged game. His subsequent twelve-year forest exile, the yaksha riddles, his refusal to abandon a loyal dog at heaven's gate — all reveal a man perpetually tested and perpetually choosing dharma, however painfully." },

{ id:"Bhima", name:"Bhima", sanskrit:"भीम", epithet:"Vrikodara — Wolf-Bellied, Son of the Wind", gender:"male", gen:15, clan:"Kuru", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Kaumodaki mace gifted by Varuna; strength of ten thousand elephants", desc:"Second Pandava and son of Vayu the wind god, Bhima was the mightiest warrior of the age in raw physical strength. He slew more Kaurava maharathis than any other Pandava — Jarasandha in a wrestling match, Hidimba, Bakasura, Kirmira, and eventually every single one of the hundred Kauravas. His vow to drink Dushasana's blood and shatter Duryodhana's thigh — both sworn after Draupadi's humiliation — he fulfilled with terrible exactness on the seventeenth and eighteenth days of battle." },

{ id:"Arjuna", name:"Arjuna", sanskrit:"अर्जुन", epithet:"Jishnu — The Invincible Bowman", gender:"male", gen:15, clan:"Kuru", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Gandiva bow, Pashupatastra, Brahmastra, Indrastra — the complete celestial arsenal", desc:"Third Pandava and son of Indra, Arjuna is universally considered the greatest archer who ever lived. He won Draupadi at the swayamvara by piercing a rotating fish's eye while looking only at its reflection. He trained under Drona, Kripa, and spent a year in Indra's heaven mastering celestial weapons directly from the gods. His moment of despair at Kurukshetra before relatives and teachers became the occasion for the Bhagavad Gita — perhaps the most consequential crisis of conscience in human literature. He slew Karna on the seventeenth day in a controversial duel that remains debated across millennia." },

{ id:"Nakula", name:"Nakula", sanskrit:"नकुल", epithet:"The Most Handsome of Men", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Sword, expert horseman and horse-healer of divine skill", desc:"Fourth Pandava and son of the Ashwini Kumaras, Nakula was considered the most physically beautiful man in the world — so handsome that Yudhishthira feared his looks would distract women during the year of hiding. He served disguised as a horse-keeper in Virata's court. A master swordsman and one of the finest horsemen of the age, he managed the entire cavalry of the Pandava army. His twin bond with Sahadeva was the closest fraternal relationship among the five brothers." },

{ id:"Sahadeva", name:"Sahadeva", sanskrit:"सहदेव", epithet:"The Silent Seer", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Sword; possessed complete knowledge of past, present and future", desc:"Youngest Pandava and twin of Nakula, Sahadeva knew the entire future of the Mahabharata war — including his own role in it — yet a divine curse forbade him from revealing it uninvited. He served as a cowherd in Virata's kingdom during hiding. He had sworn to kill Shakuni above all others, and fulfilled that vow on the eighteenth day. Legend says he gained omniscience by eating his father Pandu's brain after his death — an act prescribed to inherit wisdom." },

{ id:"Karna", name:"Karna", sanskrit:"कर्ण", epithet:"Radheya — The Tragic Hero of Dharma", gender:"male", gen:15, clan:"Kuru", importance:"high", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Vasavi Shakti (Indra's spear, one use only), Brahmastra; born with divine kavach and kundala", desc:"The greatest tragic hero of the Mahabharata — Kunti's firstborn, abandoned at birth in a basket on the Ganga, raised by the charioteer Adhiratha and his wife Radha. A warrior who equalled or surpassed Arjuna in skill yet was denied recognition at every turn due to caste. He gave away his divine armour and earrings to Indra in disguise because his oath of charity was absolute. Duryodhana's loyal friend, he fought for the Kauravas despite knowing his true Pandava identity. On the seventeenth day, his chariot wheel sank into the earth — fulfilling a brahmin's curse — and Arjuna shot him in that helpless moment. His death revealed he had known the truth all along, and had chosen loyalty and honour over birth-right." },


// ── Gen 15 · Kauravas & Allies ────────────────────────────────────────────────
{ id:"Duryodhana", name:"Duryodhana", sanskrit:"दुर्योधन", epithet:"Suyodhana — The Unyielding", gender:"male", gen:15, clan:"Kuru", importance:"high", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Mace — unmatched in the entire world; trained by Balarama himself", desc:"Eldest of Dhritarashtra's hundred sons and the primary antagonist of the Mahabharata — yet in his own telling, a man who believed he was simply defending what was rightfully his. His hatred of the Pandavas was visceral and lifelong, born of humiliation at Indraprastha's magic palace and fanned by Shakuni's constant manipulation. He refused Krishna's peace embassy, declaring he would not give the Pandavas even a needlepoint of land. His final stand in the lake — fighting Bhima with a mace after all his allies had fallen — was the most valiant and tragic last act in the epic. He died as he lived: refusing to yield." },

{ id:"Dushasana", name:"Dushasana", sanskrit:"दुःशासन", epithet:"The Violator", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow and sword; immense physical strength", desc:"Second of the Kauravas and Duryodhana's most devoted enforcer. It was Dushasana who dragged Draupadi by her hair into the Kaurava court and attempted to disrobe her — the act that sealed the doom of the entire Kuru dynasty. Bhima swore to tear open his chest and drink his blood. On the seventeenth day Bhima fulfilled that oath with terrible literalness, smearing the blood on Draupadi's unbound hair she had kept loose since that day of humiliation." },

{ id:"Vikarna", name:"Vikarna", sanskrit:"विकर्ण", epithet:"The Righteous Kaurava", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow — skilled warrior of the Kaurava ranks", desc:"Third son of Dhritarashtra and the one Kaurava who publicly opposed the humiliation of Draupadi in the dice hall, arguing forcefully that she had been staked illegally. His solitary voice of conscience in the Kaurava court stands as the most honourable moment among the hundred brothers. He fought loyally for his clan in the war and was slain by Bhima, who wept as he killed him — acknowledging that Vikarna deserved better than the brothers he was born among." },

{ id:"Dhrishtadyumna", name:"Dhrishtadyumna", sanskrit:"धृष्टद्युम्न", epithet:"Fire-Born Commander of the Pandavas", gender:"male", gen:15, clan:"Panchala", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Born holding bow and arrow from the yajna fire; master of vyuha formations", desc:"Son of Drupada born from the yajna fire specifically to kill Dronacharya — a destiny he fulfilled on the fifteenth day when he beheaded the meditating acharya, an act condemned even by the Pandavas as adharmic. He served as supreme commander of the entire Pandava army, organising its seven-akshauhini forces. His tactical acumen offset the Kauravas' numerical advantage for seventeen days. He was ultimately killed in his sleep by Ashwatthama during the horrifying night massacre that ended the war." },

{ id:"Shikhandi", name:"Shikhandi", sanskrit:"शिखण्डी", epithet:"The Instrument of Bhishma's Death", gender:"other", gen:15, clan:"Panchala", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Bow — the living weapon whose very presence paralysed Bhishma", desc:"Born female as Shikhandini, reincarnation of Amba who had killed herself vowing to destroy Bhishma, and transformed male through the boon of a Yaksha. Bhishma had vowed never to strike one who had been a woman — so when Arjuna positioned Shikhandi before him on the tenth day, the grandsire lowered his bow and received a storm of arrows. Shikhandi's whole existence was a single arrow aimed across lifetimes at one man, and it struck true." },

{ id:"Ashwatthama", name:"Ashwatthama", sanskrit:"अश्वत्थामा", epithet:"The Immortal Avenger", gender:"male", gen:15, clan:"Kuru", importance:"high", allegiance:"Kaurava", chiranjeevi:true, avatar:null, weapon:"Brahmastra — the absolute weapon he released on Uttara's womb; Narayanastra", desc:"Son of Dronacharya and Kripi, born with a gem in his forehead that granted immunity to hunger, thirst, and fear. After his father's treacherous killing, Ashwatthama led a night raid on the Pandava camp, massacring Dhrishtadyumna and the Upapandavas in their sleep. He then released the Brahmastra against Uttara's unborn child — an act so heinous that Krishna cursed him to wander the earth for three thousand years, his forehead wound never healing. A Chiranjeevi, he still walks the world, the gem torn from his brow, the living wound of the Mahabharata's greatest atrocity." },

{ id:"Satyaki", name:"Satyaki", sanskrit:"सात्यकि", epithet:"Yuyudhana — The Unbreakable", gender:"male", gen:15, clan:"Yadava", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Bow trained directly by Arjuna; equal in skill to his own teacher", desc:"A Yadava warrior of the Vrishni clan and Arjuna's devoted student and closest friend. When the Yadava army was divided at Kurukshetra, Satyaki alone chose the Pandava side over Krishna's military forces. He single-handedly broke through the Kaurava formation to reach Arjuna on the fourteenth day in one of the war's greatest solitary charges. He survived the war, though the Yadava civil war at Prabhasa later claimed his life alongside most of his clan." },

{ id:"Vrushali", name:"Vrushali", sanskrit:"वृषाली", epithet:"The Faithful Wife of Karna", gender:"female", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"The devoted wife of Karna, given to him by his foster father Adhiratha from their own community of charioteers. She stood beside Karna through every humiliation the Kuru court inflicted on him — the sneers about his birth, the denial of the right to duel, the constant caste slights. She bore him sons including the valiant Vrishasena and Vrishaketu. When Karna fell on the seventeenth day, Vrushali's grief was absolute — she had loved a king that the world refused to crown." },

{ id:"Bhanumati", name:"Bhanumati", sanskrit:"भानुमती", epithet:"Queen of the Kauravas", gender:"female", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"The beautiful and spirited wife of Duryodhana, princess of Kalinga. She shared a close friendship with Karna — famous for the scene where Karna placed his hands on her shoulder during a game and the pearl necklace broke; Duryodhana walked in and rather than suspecting, helped pick up the pearls, revealing the depth of trust between the three. She bore Duryodhana a son, Lakshmana Kumara, and a daughter Lakshmanaa — both of whom perished in the war." },

{ id:"Hidimbi", name:"Hidimbi", sanskrit:"हिडिम्बी", epithet:"The Rakshasi Who Chose Love", gender:"female", gen:15, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Rakshasa shapeshifting and supernatural forest power", desc:"A rakshasi (demoness) of the Kamyaka forest who fell in love with Bhima when he came to kill her brother Hidimba. She transformed herself into a beautiful woman and openly declared her love — an act of remarkable courage for its era. After Bhima slew her brother in combat, she married Bhima with Kunti's blessing and bore the mighty Ghatotkacha, who would become a crucial weapon in the Pandava arsenal at Kurukshetra. She is the Mahabharata's most tender and unconventional love story." },


// ── Gen 15 · Arjuna's Wives & Allied Kings ────────────────────────────────────
{ id:"Ulupi", name:"Ulupi", sanskrit:"उलूपी", epithet:"The Naga Princess", gender:"female", gen:15, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Nagaloka powers — brought Arjuna back from death with the Mritasanjivani gem", desc:"Princess of the Naga kingdom beneath the Ganga, Ulupi drew Arjuna into her underwater realm during his twelve-year exile and married him for a single night, bearing the son Iravan. She possessed the divine Mritasanjivani gem of her serpent kin. After Arjuna was slain by his own son Babruvahana in a fateful duel, it was Ulupi who placed the gem on his chest and restored him to life — her love outlasting death itself." },

{ id:"Chitrangada2", name:"Chitrangada", sanskrit:"चित्राङ्गदा", epithet:"Warrior Princess of Manipur", gender:"female", gen:15, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Trained warrior — fought in battle like a man", desc:"Princess of the kingdom of Manipura and daughter of King Chitravahana, she was raised as a son by her father in the absence of a male heir. She met Arjuna during his forest exile, fell in love, and proposed marriage herself — on the condition that their son Babruvahana remain in Manipur as its heir. Fearless and self-possessed, she is one of the Mahabharata's most modern heroines, choosing her own terms for love and lineage." },

{ id:"Shalya", name:"Shalya", sanskrit:"शल्य", epithet:"King of Madra — Karna's Charioteer", gender:"male", gen:15, clan:"Madra", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Immense strength; maharathi — supreme charioteer", desc:"King of Madra and maternal uncle of Nakula and Sahadeva, Shalya marched to help the Pandavas but was tricked by Duryodhana's lavish hospitality into pledging for the Kaurava side. He served as Karna's charioteer on the seventeenth day, secretly undermining Karna's morale at Krishna's instruction by constant belittlement — a painful irony for both men. After Karna's death he became commander-in-chief for the final day, before Yudhishthira slew him in single combat." },

{ id:"Virata", name:"Virata", sanskrit:"विराट", epithet:"King of Matsya", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Seasoned warrior and cavalry commander", desc:"King of the Matsya kingdom who unknowingly harboured all five Pandavas and Draupadi during their thirteenth year of disguised exile. His kingdom became the launching pad for the Mahabharata war — it was at Virata's court that Arjuna, disguised as the dance teacher Brihannala, single-handedly routed the entire Kaurava army that came to steal Virata's cattle. His daughter Uttara was given as a daughter-in-law by the Pandavas — she married Abhimanyu, linking Matsya to the Kuru destiny." },

{ id:"Kritavarma", name:"Kritavarma", sanskrit:"कृतवर्मा", epithet:"The Yadava on the Wrong Side", gender:"male", gen:15, clan:"Yadava", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow — a maharathi of great skill and endurance", desc:"A powerful Yadava warrior of the Satvata clan who chose to fight for the Kauravas, commanding the Narayani Sena — Krishna's personal army of one akshauhini — against the Pandavas. He was one of only three survivors of the Kaurava side along with Ashwatthama and Kripacharya. He participated in the notorious night raid on the Pandava camp. He later died in the Yadava civil conflict at Prabhasa when Satyaki accused him of cowardice for the night raid and the fight escalated into the obliteration of the Yadava race." },

{ id:"Bhuri", name:"Bhuri", sanskrit:"भूरि", epithet:"Son of Somadatta", gender:"male", gen:15, clan:"Kuru", importance:"low", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow — gifted Kaurava archer", desc:"Eldest son of Somadatta and a warrior on the Kaurava side, Bhuri was known for his enormous wealth donated at the Kurukshetra yajnas. He fell in battle during the great war, one of the many princes of the extended Kuru clan who perished fighting cousins on the same ancestral ground." },

{ id:"Bhurishravas", name:"Bhurishravas", sanskrit:"भूरिश्रवस्", epithet:"The Honourable Fallen", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow — considered one of the premier archers of the Kaurava host", desc:"Son of Somadatta and one of the most honoured warriors in the Kaurava army. On the fourteenth day he was in the act of dragging Satyaki by the hair when Arjuna severed his arm. Bhurishravas sat down, renouncing battle to die in prayopavesa (ritual fast). Satyaki then beheaded him — an act condemned by all as deeply adharmic, since one who had renounced combat was inviolable. His death is one of the war's most controversial moral episodes." },

{ id:"Jarasandha", name:"Jarasandha", sanskrit:"जरासन्ध", epithet:"Joined-at-Birth King of Magadha", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Immense physical strength — fought Balarama and Krishna simultaneously eighteen times", desc:"The mighty king of Magadha born in two halves joined by the demoness Jara, Jarasandha was the most powerful mortal king of the age and father-in-law of Kamsa. He attacked Mathura seventeen times forcing the Yadavas to retreat to Dwarka. His capture of kings for sacrifice to Shiva was ended by Bhima, who killed him in a brutal thirteen-day wrestling match — guided by Krishna's secret signal revealing Jarasandha's one weakness: his body must be torn apart in opposite directions, back to the original split." },

{ id:"Dushala", name:"Dushala", sanskrit:"दुःशला", epithet:"The Lone Daughter of Dhritarashtra", gender:"female", gen:15, clan:"Kuru", importance:"low", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"The only daughter among Dhritarashtra's hundred-and-one children, Dushala was given in marriage to Jayadratha, king of Sindhu. Her husband was slain by Arjuna avenging Abhimanyu's death. Her son Suratha also died in battle. A woman surrounded entirely by the war's destruction, she appears briefly when Arjuna spares her grandson out of compassion for her grief — a rare moment of mercy in the Mahabharata's relentless tide of loss." },

{ id:"Yuyutsu", name:"Yuyutsu", sanskrit:"युयुत्सु", epithet:"The Kaurava Who Chose Dharma", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Bow — fought on the Pandava side despite Kaurava birth", desc:"Son of Dhritarashtra by Sukhada, a Vaishya woman, making him a half-brother to all hundred Kauravas. On the eve of the Kurukshetra war he crossed the battlefield to join the Pandava side — the only son of Dhritarashtra to survive the eighteen days. Yudhishthira entrusted him with protecting Hastinapura during the Pandavas' final journey. He is the Mahabharata's quiet testament that lineage does not determine dharma — choice does." },


// ── Gen 16 · Next Generation ──────────────────────────────────────────────────
{ id:"Abhimanyu", name:"Abhimanyu", sanskrit:"अभिमन्यु", epithet:"The Unbroken — Son of Arjuna", gender:"male", gen:16, clan:"Kuru", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Gandiva-level archery; learned Chakravyuha entry in the womb but not exit", desc:"Son of Arjuna and Subhadra, Abhimanyu learned the art of breaking the deadly Chakravyuha formation while still in his mother's womb — but Subhadra fell asleep before Krishna could teach the exit. On the thirteenth day of battle, barely sixteen years old, he broke into the Padmavyuha alone and fought off the entire Kaurava host single-handedly until six maharathis — Drona, Karna, Ashwatthama, Kripa, Kritavarma, and Brihatbala — conspired to surround and destroy him, shattering his bow, his chariot, and finally his life. His death was the most universally mourned of the war, and Arjuna's subsequent vow to kill Jayadratha before sunset the next day nearly broke the boundaries of time itself." },

{ id:"Ghatotkacha", name:"Ghatotkacha", sanskrit:"घटोत्कच", epithet:"The Rakshasa Warrior", gender:"male", gen:16, clan:"Kuru", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Rakshasa maya — illusions, shapeshifting, and supernatural warfare that was most deadly at night", desc:"Son of Bhima and the rakshasi Hidimbi, born with a head shaped like a pot — hence his name. He answered his father's call the moment the war began and led the Pandava forces in night fighting where rakshasa powers are supreme. Karna, unable to stop the devastation, was forced to use the Vasavi Shakti — his one-use divine spear from Indra, reserved for Arjuna — to kill Ghatotkacha. Krishna rejoiced at this, for the greatest weapon against Arjuna had been spent. Ghatotkacha's death was one of the war's great tactical sacrifices." },

{ id:"Pradyumna", name:"Pradyumna", sanskrit:"प्रद्युम्न", epithet:"Son of Krishna, Reborn Kama", gender:"male", gen:16, clan:"Yadava", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Divine bow — inherited his father's celestial archery skill", desc:"Son of Krishna and Rukmini, Pradyumna is considered an incarnation of Kama (the god of love), reborn after Shiva reduced him to ash. He was abducted at birth by the demon Shambara and raised in ignorance; the apsara Mayavati (Rati reborn) revealed his identity and taught him divine illusion. He slew Shambara, returned to Dwarka, and became one of the greatest Yadava warriors. He married Rukmavati, daughter of Rukmi, and fathered Aniruddha, who would woo Usha and trigger the Yadava-Bana war." },

{ id:"Samba", name:"Samba", sanskrit:"साम्ब", epithet:"The Rebellious Son", gender:"male", gen:16, clan:"Yadava", importance:"medium", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:"Bow and Yadava martial training", desc:"Son of Krishna and Jambavati, Samba was famed for his extraordinary beauty — which he inherited from both parents — and for his arrogant, reckless nature. He abducted Duryodhana's daughter Lakshmana from her swayamvara and was captured by the Kauravas until Balarama's furious intervention freed him. Most fatefully, Samba mocked a group of sages by dressing as a pregnant woman; their curse was that he would 'give birth' to an iron pestle that would destroy the Yadava race — the instrument of the clan's self-annihilation at Prabhasa." },

{ id:"Iravan", name:"Iravan", sanskrit:"इरावन्", epithet:"Son of Arjuna and the Naga Princess", gender:"male", gen:16, clan:"Kuru", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Naga powers combined with Pandava archery", desc:"Son of Arjuna and the Naga princess Ulupi, Iravan inherited both his father's warrior skill and his mother's supernatural Naga powers. He fought valiantly in the opening days of the Kurukshetra war before being slain by the rakshasa Alambusha on the eighth day. In South Indian tradition, particularly among the Koothandavar cult of Tamil Nadu, Iravan is venerated as a warrior-god, and his marriage the night before his death to Krishna in the form of Mohini is a celebrated folk tradition." },

{ id:"Babruvahana", name:"Babruvahana", sanskrit:"बभ्रुवाहन", epithet:"The Son Who Slew His Father", gender:"male", gen:16, clan:"Kuru", importance:"medium", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:"Bow — inherited Arjuna's skill; slew his own father in righteous combat", desc:"Son of Arjuna and Chitrangada of Manipur, raised as king of Manipura by his mother's terms. When Arjuna arrived during the Ashwamedha horse sacrifice, Babruvahana — goaded by his step-mother Ulupi — fought and actually killed Arjuna in single combat. Ulupi then used the Naga gem to restore Arjuna's life, revealing she had engineered the whole encounter to free Arjuna from a brahmin's curse incurred during the Mahabharata war. Father and son reconciled, and Babruvahana paid the tribute of Manipur to the Pandava empire." },

{ id:"Uttara", name:"Uttara", sanskrit:"उत्तरा", epithet:"Princess of Matsya, Mother of Parikshit", gender:"female", gen:16, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"Daughter of King Virata of Matsya, she was taught dance by Arjuna during his year of disguise in her father's court. She married Abhimanyu, the son of her own teacher — a union that bound Matsya to the Pandava cause. Widowed at Abhimanyu's death on the thirteenth day, she was pregnant with Parikshit when Ashwatthama released the Brahmastra at her womb. Krishna personally entered the womb in his subtle form to protect the unborn child — ensuring the survival of the Kuru lineage." },

{ id:"LakshmanaKumara", name:"Lakshmana Kumara", sanskrit:"लक्ष्मण कुमार", epithet:"Son of Duryodhana", gender:"male", gen:16, clan:"Kuru", importance:"low", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow — trained Kaurava warrior", desc:"The young son of Duryodhana and Bhanumati, Lakshmana Kumara fought in the Kurukshetra war and was slain by Abhimanyu on the very thirteenth day — the same day Abhimanyu himself died. His death struck Duryodhana with grief even as he continued pursuing the war. He represents the generation that had no say in the conflict born of their fathers' hatred, yet paid its full price." },

{ id:"Upapandavas", name:"Upapandavas", sanskrit:"उपपाण्डव", epithet:"The Five Sons of Draupadi", gender:"male", gen:16, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Trained by Arjuna and Dhrishtadyumna in all weapons", desc:"The five sons born of Draupadi and each of the five Pandavas — Prativindhya (Yudhishthira's), Sutasoma (Bhima's), Shrutakarma (Arjuna's), Shatanika (Nakula's), and Shrutasena (Sahadeva's). All five were slain in their sleep during Ashwatthama's horrific night massacre of the Pandava camp, mistaken for the Pandavas themselves. Their deaths — of children, in sleep, by a disgraced general's revenge — represent the war's most unconscionable act and the price the next generation paid for their elders' conflict." },

{ id:"Vrishasena", name:"Vrishasena", sanskrit:"वृषसेन", epithet:"Karna's Valiant Son", gender:"male", gen:16, clan:"Kuru", importance:"low", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow — trained warrior in his father's image", desc:"The eldest and most celebrated son of Karna and Vrushali, Vrishasena fought fiercely for the Kauravas and was slain by Arjuna on the seventeenth day — shortly before Arjuna killed Karna himself. His death enraged Karna, whose anguish at losing his son while still fighting added another layer of tragedy to the day's already devastating events. He inherited his father's natural grace and warrior's code, and died as his father did — unbroken." },


// ── Gen 17 · Post-War & Successors ───────────────────────────────────────────
{ id:"Parikshit", name:"Parikshit", sanskrit:"परीक्षित्", epithet:"The Last Kuru King", gender:"male", gen:17, clan:"Kuru", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Bow — a mighty and righteous king", desc:"Son of Abhimanyu and Uttara, Parikshit was the sole surviving Kuru heir — saved in the womb from Ashwatthama's Brahmastra by Krishna himself. He ruled Hastinapura with great justice after the Pandavas' departure, and the Bhagavata Purana is structured as his final seven days of listening to Shuka's recitation of Vishnu's glories after being cursed to die by snakebite. The story of his death from Takshaka's bite, and his son Janamejaya's revenge sacrifice, closes the Dvapara Yuga cycle." },

{ id:"Madravati", name:"Madravati", sanskrit:"मद्रावती", epithet:"Queen of Parikshit", gender:"female", gen:17, clan:"Kuru", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"The queen consort of King Parikshit and mother of Janamejaya, through whom the Kuru lineage continued into the Kali Yuga. Her patient devotion sustained the royal household during the turbulent post-war years of reconstruction and the existential threats that haunted the last Kuru king." },

{ id:"Aniruddha", name:"Aniruddha", sanskrit:"अनिरुद्ध", epithet:"Grandson of Krishna", gender:"male", gen:17, clan:"Yadava", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Mace and bow — inherited Yadava martial tradition", desc:"Son of Pradyumna and Rukmavati and grandson of Krishna, Aniruddha was famously abducted by the princess Usha of the asura Banasura's kingdom, who had seen him in a dream and fallen in love. Her friend Chitralekha painted portraits of every being in the cosmos until Usha identified him. This led to the great war between Krishna and Banasura, ultimately resolved when Shiva intervened on Banasura's behalf and Krishna spared the demon. Aniruddha married Usha and continued the Yadava line." },

{ id:"Janamejaya", name:"Janamejaya", sanskrit:"जनमेजय", epithet:"The Snake-Sacrifice King", gender:"male", gen:17, clan:"Kuru", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Royal authority and fire of sacrifice", desc:"Son of Parikshit, Janamejaya conducted the Sarpa Satra — the great snake sacrifice designed to exterminate the entire serpent race in revenge for Takshaka's killing of his father. It was at this very sacrifice that the sage Vaishampayana first recited the Mahabharata to Janamejaya at Vyasa's instruction — making Janamejaya's grief and vengeance the framing narrative of the entire epic. The sacrifice was halted by the brahmin Astika to save the serpent Takshaka." },

// ── Krishna's Queens ──────────────────────────────────────────────────────────
{ id:"Rukmini", name:"Rukmini", sanskrit:"रुक्मिणी", epithet:"Lakshmi Incarnate — Chief Queen of Dwarka", gender:"female", gen:15, clan:"Yadava", importance:"high", allegiance:"Pandava", chiranjeevi:false, avatar:"Lakshmi", weapon:null, desc:"Princess of Vidarbha and the principal queen of Krishna, considered an incarnation of Lakshmi herself. She sent a secret letter to Krishna begging him to rescue her from a forced marriage to Shishupala, arranged by her brother Rukmi who despised Krishna. Krishna arrived on her wedding day and abducted her in full view of assembled kings — she willingly stepped into his chariot, choosing her own husband with sovereign grace. Their love story is the Bhagavata Purana's ideal of devotion: personal, passionate, and cosmically destined." },

{ id:"Satyabhama", name:"Satyabhama", sanskrit:"सत्यभामा", epithet:"The Fierce Queen of Krishna", gender:"female", gen:15, clan:"Yadava", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Fought alongside Krishna against the asura Narakasura", desc:"Daughter of the Yadava chieftain Satrajit and one of Krishna's most beloved queens, renowned for her fierce spirit and jealousy that matched her beauty. She fought beside Krishna on the back of Garuda to slay the demon Narakasura, personally delivering the killing blow. She once famously 'purchased' Krishna from Narada by placing him on a scale and balancing it with a single tulsi leaf offered with pure devotion — a tale of love defeating material measure." },

{ id:"Jambavati", name:"Jambavati", sanskrit:"जाम्बवती", epithet:"Daughter of the Bear-King", gender:"female", gen:15, clan:"Yadava", importance:"medium", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"Daughter of Jambavan — the great bear-warrior who aided Rama in the Ramayana — and one of Krishna's eight principal queens. She became Krishna's wife after a twenty-one-day battle between Krishna and her father over the Syamantaka jewel. Jambavan, realising his opponent could only be Vishnu himself, surrendered and offered his daughter and the gem. She bore Krishna the proud and beautiful Samba." },

{ id:"Rukmavati", name:"Rukmavati", sanskrit:"रुक्मावती", epithet:"Wife of Pradyumna", gender:"female", gen:16, clan:"Yadava", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"Daughter of Rukmi — Rukmini's resentful brother — and wife of Pradyumna, Krishna's son. Her marriage linked the households of Vidarbha and Dwarka despite Rukmi's ongoing bitterness toward Krishna. She bore Aniruddha, who continued the Yadava lineage. Her family connection ensured a fragile peace between Rukmi and the Yadavas that lasted until Rukmi's death at Balarama's hands during a dice game argument." },

{ id:"Uttarakumara", name:"Uttara Kumara", sanskrit:"उत्तर कुमार", epithet:"Prince of Matsya", gender:"male", gen:15, clan:"Kuru", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Bow — though he initially fled in fear, he became a loyal Pandava ally", desc:"Son of King Virata and brother of Uttara the princess, he boasted loudly of his martial prowess before the battle at Virata's cattle pen but fled in terror when he saw the actual Kaurava forces. Arjuna in disguise caught him and drove the chariot himself — revealing his true identity only after routing the entire Kaurava army. Uttara became a devoted Pandava ally and fought at Kurukshetra, dying honourably in battle." },

{ id:"Vrishaketu", name:"Vrishaketu", sanskrit:"वृषकेतु", epithet:"Karna's Surviving Son", gender:"male", gen:16, clan:"Kuru", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Bow — eventually trained by Arjuna himself", desc:"The sole surviving son of Karna and Vrushali after the Kurukshetra war. In a remarkable act of atonement, Arjuna — who had killed Karna — took Vrishaketu under his protection and trained him personally in archery. Vrishaketu fought alongside Arjuna during the Ashwamedha horse sacrifice campaigns, earning renown as a warrior in his own right. His story is the Mahabharata's quiet grace note: the enemy's son, raised by the victor, healing the wound that was never truly about hatred." },


// ── Support Cast ──────────────────────────────────────────────────────────────
{ id:"Prashati", name:"Prashati", sanskrit:"पृषत", epithet:"King of Panchala", gender:"male", gen:12, clan:"Panchala", importance:"low", allegiance:"Pre-war", chiranjeevi:false, avatar:null, weapon:null, desc:"King of Panchala and father of Drupada, Prashati was a close friend of sage Bharadwaja and sent his son to study at the sage's ashrama alongside the young Drona. This childhood friendship — and its eventual shattering — became the seed of the enmity between Drona and Drupada that would bear its terrible fruit in the yajna that produced Draupadi and Dhrishtadyumna, reshaping the entire war." },

{ id:"Ekalavya", name:"Ekalavya", sanskrit:"एकलव्य", epithet:"The Self-Taught Archer", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Self-mastered archery that surpassed even Arjuna's skill", desc:"A Nishada prince who built a clay statue of Drona and taught himself archery through sheer devotion, reaching a level that surpassed Arjuna. When Drona demanded his right thumb as gurudakshina to maintain Arjuna's supremacy, Ekalavya cut it off without hesitation — the most debated act of guru-devotion in all of Indian literature. He later fought on the Kaurava side and was killed by Krishna during the campaign against Jarasandha. His sacrifice remains the Mahabharata's sharpest question about caste, merit, and justice." },

{ id:"Amba", name:"Amba", sanskrit:"अम्बा", epithet:"The Undying Grievance", gender:"female", gen:13, clan:"Kuru", importance:"medium", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:"Reborn as Shikhandi — a weapon in human form", desc:"Eldest of the three Kashi princesses abducted by Bhishma for Vichitravirya. She had already given her heart to King Shalva and was released by Bhishma, but Shalva rejected her as another man's prize. She returned to Bhishma demanding he marry her — he refused, bound by his vow of celibacy. Carrying her burning humiliation to every court and sage in the land and finding no justice, she performed severe penance and received a garland of lotuses that would destroy Bhishma. Unable to find a warrior to wear it, she finally immolated herself, vowing to be reborn as Bhishma's killer — fulfilled when she was reborn as Shikhandi." },

{ id:"Jayadratha", name:"Jayadratha", sanskrit:"जयद्रथ", epithet:"King of Sindhu — Abhimanyu's Gatekeeper", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Boon from Shiva: could hold back all Pandavas except Arjuna for one day", desc:"King of Sindhu and husband of Dushala, Dhritarashtra's daughter. He held the entrance of the Chakravyuha closed against all Pandavas except Arjuna on the thirteenth day, trapping Abhimanyu inside to be destroyed. Arjuna swore to kill him by sunset the next day or immolate himself — a vow so absolute that Krishna made the sun disappear at sunset before Jayadratha was found, then revealed the trick. As Jayadratha celebrated his survival, Arjuna's arrow severed his head, and his father's curse caused it to fall into the lap of the very man who had given Jayadratha his terrible boon." },

{ id:"Kuntibhoja", name:"Kuntibhoja", sanskrit:"कुन्तिभोज", epithet:"Foster Father of Kunti", gender:"male", gen:13, clan:"Kuru", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"A generous and childless king, cousin of Shurasena, who adopted Pritha — Shurasena's firstborn daughter — and raised her as his own beloved child Kunti. His name became part of her identity. He fought on the Pandava side at Kurukshetra out of deep affection for his foster daughter and grandsons, contributing his armies to the seven-akshauhini Pandava host." },

{ id:"Nanda", name:"Nanda", sanskrit:"नन्द", epithet:"The Cowherd Father of Krishna", gender:"male", gen:14, clan:"Yadava", importance:"medium", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"Chief of the Gokul cowherds and the man who raised Krishna as his own beloved son. On the night of Krishna's birth, Vasudeva secretly brought the infant across the Yamuna and exchanged him for Nanda's newborn daughter. Nanda raised Krishna through all his childhood glories — the butter thefts, the Govardhana lifting, the Rasa Lila — loving him with a father's uncomplicated, joyful devotion that even the cosmos could not replicate." },

{ id:"Yashoda", name:"Yashoda", sanskrit:"यशोदा", epithet:"The Mother Who Bound God", gender:"female", gen:14, clan:"Yadava", importance:"medium", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"Wife of Nanda and Krishna's beloved foster mother, whose love for the child was so pure and total that she alone could scold the lord of the cosmos for stealing butter. In the most intimate divine moment of the Bhagavata Purana, she tried to bind Krishna as punishment — and found that no rope was ever quite long enough, until Krishna himself allowed it out of love for her tears. She saw the entire universe in his open mouth when he ate mud, then forgot the vision because maternal love is its own kind of divine grace." },

{ id:"Radha", name:"Radha", sanskrit:"राधा", epithet:"The Supreme Devotee — Eternal Beloved", gender:"female", gen:14, clan:"Yadava", importance:"high", allegiance:"Divine", chiranjeevi:false, avatar:"Lakshmi", weapon:null, desc:"The transcendent beloved of Krishna in Gokul, Radha represents the highest form of bhakti — selfless, total, consuming love that asks nothing in return. Though not mentioned by name in the Mahabharata itself, she permeates its spiritual core through the Bhagavata Purana and later traditions. Her love for Krishna is considered the perfect mirror of the soul's love for the divine — and her grief at his departure from Gokul, never to return, is the sweetest sorrow in all of Indian devotional poetry." },

{ id:"Rukmi", name:"Rukmi", sanskrit:"रुक्मी", epithet:"Rukmini's Bitter Brother", gender:"male", gen:15, clan:"Yadava", importance:"medium", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:"Bow — a skilled warrior who fought both sides", desc:"Crown prince of Vidarbha and Rukmini's elder brother, Rukmi despised Krishna as an unworthy match for his royal sister and arranged her marriage to Shishupala instead. When Krishna eloped with Rukmini, Rukmi pursued them and was defeated in combat; Krishna spared his life at Rukmini's pleading but shaved his head as public humiliation. He founded the city of Bhojakatha and spent his life in the shadow of that shame. He was killed by Balarama during a dice argument at Aniruddha's wedding — a death that none mourned and none could entirely justify." },

{ id:"Usha", name:"Usha", sanskrit:"उषा", epithet:"Daughter of Banasura", gender:"female", gen:17, clan:"Divine", importance:"low", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"Daughter of the demon king Banasura and devotee of Shiva, Usha dreamed of a beautiful young man and fell desperately in love before ever meeting him. Her friend Chitralekha used her divine artistic powers to paint every being in the three worlds until Usha identified the young man as Aniruddha, grandson of Krishna. Chitralekha abducted Aniruddha from Dwarka, setting off the war between Krishna and Banasura. Usha married Aniruddha and became the bridge between the asura and Yadava worlds." },


// ── Final Support Cast ────────────────────────────────────────────────────────
{ id:"Sukhada", name:"Sukhada", sanskrit:"सुखदा", epithet:"Vaishya Queen of Dhritarashtra", gender:"female", gen:14, clan:"Kuru", importance:"low", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"A Vaishya woman who became one of Dhritarashtra's consorts and mother of Yuyutsu — the one son of Dhritarashtra who defected to the Pandava side on the eve of the war. Though her status was lower than Gandhari's, her son proved to be the most morally courageous of all Dhritarashtra's children, suggesting she raised him with a clarity the royal court could not provide." },

{ id:"Adhiratha", name:"Adhiratha", sanskrit:"अधिरथ", epithet:"Foster Father of Karna", gender:"male", gen:14, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"A charioteer of the Kuru kingdom who found the infant Karna floating in a basket on the Ganga and raised him with unconditional love alongside his wife Radha. He gave Karna his first identity — Radheya, son of Radha — before the world gave him titles and humiliations. His simple, dignified love for his adopted son is one of the Mahabharata's quiet testaments to the truth that a parent is the one who stays, not merely the one who gives birth." },

{ id:"Shishupala", name:"Shishupala", sanskrit:"शिशुपाल", epithet:"The King Whose Hundred Sins Were Forgiven", gender:"male", gen:15, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow and sword — a maharathi of considerable skill", desc:"King of Chedi and cousin of Krishna, born with three eyes and four arms — a celestial sign that he was destined to be killed by a divine hand. His mother extracted a promise from Krishna to forgive a hundred of Shishupala's offences. At Yudhishthira's Rajasuya sacrifice, Shishupala publicly insulted Krishna one hundred and one times — on the hundred-and-first, Krishna's Sudarshana Chakra severed his head. The divine light from Shishupala's body merged into Krishna, revealing he was a liberated soul all along, his hatred a form of constant remembrance of the divine." },

{ id:"Bhishmaka", name:"Bhishmaka", sanskrit:"भीष्मक", epithet:"King of Vidarbha", gender:"male", gen:14, clan:"Yadava", importance:"low", allegiance:"Neutral", chiranjeevi:false, avatar:null, weapon:null, desc:"The noble king of Vidarbha and father of Rukmini and Rukmi. He admired Krishna greatly and would have gladly given his daughter to him — but bowed to pressure from his son Rukmi who had allied with Jarasandha and Shishupala. His helplessness to prevent his daughter's abduction-marriage was real grief, but Rukmini's happiness with Krishna ultimately reconciled him to the divine design of her life." },

{ id:"Sudeshna", name:"Sudeshna", sanskrit:"सुदेष्णा", epithet:"Queen of Virata", gender:"female", gen:15, clan:"Kuru", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:null, desc:"Queen of King Virata of Matsya, in whose court Draupadi served in disguise as a sairandhri (skilled hairdresser) named Malini during the Pandavas' thirteenth year of exile. Sudeshna treated Draupadi with reasonable kindness but sent her to her brother Kichaka, whose subsequent assault on Draupadi led Bhima to kill him — nearly unmasking the Pandavas' identities seven months before their year of hiding was complete." },

{ id:"Uluka", name:"Uluka", sanskrit:"उलूक", epithet:"Son of Shakuni, Kaurava Messenger", gender:"male", gen:15, clan:"Gandhara", importance:"low", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:"Bow — fought on the Kaurava side", desc:"Son of Shakuni and a warrior in the Kaurava army. He served as Duryodhana's messenger to the Pandavas on the eve of the Kurukshetra war, delivering a provocative speech designed to inflame rather than negotiate — a final act of Shakuni's dice-playing with words. He was slain by Sahadeva during the war, his father's fate following shortly after at the same hands." },

{ id:"Uttaravirata", name:"Uttara (Virata's son)", sanskrit:"उत्तर", epithet:"Prince of Matsya", gender:"male", gen:15, clan:"Kuru", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Bow — died on the first day of the Kurukshetra war", desc:"Son of King Virata, Uttara was slain by Shalya on the very first day of the Kurukshetra war — the opening casualty of the conflict his father had helped initiate by hosting the Pandavas. His death grieved Virata enormously, yet did not shake his alliance with the Pandavas. He is the war's first named fallen hero on the Pandava side, his death a portent of the seventeen days of carnage to follow." },

{ id:"Dhrishtaketu", name:"Dhrishtaketu", sanskrit:"धृष्टकेतु", epithet:"King of Chedi, Pandava Ally", gender:"male", gen:15, clan:"Panchala", importance:"low", allegiance:"Pandava", chiranjeevi:false, avatar:null, weapon:"Bow — commanded the Chedi forces for the Pandavas", desc:"Son of Shishupala and king of Chedi after his father's death at Krishna's hands. Despite the circumstances of his father's death, Dhrishtaketu chose to ally with the Pandavas at Kurukshetra — perhaps recognising that righteous destiny had not wronged his father but freed him. He commanded Chedi's forces as part of the Pandava seven-akshauhini army and was killed in battle by Drona." },

{ id:"Lakshmana", name:"Lakshmana", sanskrit:"लक्ष्मणा", epithet:"Duryodhana's Daughter, Samba's Wife", gender:"female", gen:16, clan:"Kuru", importance:"low", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"Daughter of Duryodhana and Bhanumati, Lakshmana was abducted from her own swayamvara by Samba, son of Krishna, who had fallen in love with her. The audacious elopement infuriated the Kauravas who captured Samba — only releasing him after Balarama arrived with his plough and threatened to drag Hastinapura into the river. Lakshmana and Samba's union wove an unlikely thread of love between the two most opposed households of the age." },

{ id:"Vrishaketu2", name:"Adhiratha's wife Radha", sanskrit:"राधा (अधिरथ-पत्नी)", epithet:"Foster Mother of Karna", gender:"female", gen:14, clan:"Kuru", importance:"medium", allegiance:"Kaurava", chiranjeevi:false, avatar:null, weapon:null, desc:"The charioteer's wife who pulled the infant Karna from the river basket and gave him his first name — Radheya, son of Radha. She raised him with complete maternal devotion, shielding him from the questions of birth that would haunt his later life. Her love was his only uncomplicated inheritance in a world that questioned his right to everything else. She is deliberately different from the cowherd Radha of Gokul — two women named Radha, both offering the Mahabharata's deepest forms of unconditional love." },

]; // ═══ END OF CHARACTER DATA ═══
// Total: ~130 characters spanning Gen 0–17

// Derived stats for UI counters
const charMap = Object.fromEntries(characters.map(c => [c.id, c]));
const totalCount = characters.length;
const generationCount = new Set(characters.map(c => c.gen)).size;
const chiranjeeviCount = characters.filter(c => c.chiranjeevi).length;
const divineCount = characters.filter(c => c.clan === 'Divine' || c.avatar).length;












